---
- name: Setup of Dev environment for native windows client
  hosts: win
  tasks:
    - name: "install chocolatey and extensions"
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
           - chocolatey-windowsupdate.extension
           - chocolatey-dotnetfx.extension
          state: present
    - name: install basic dev packages
      win_chocolatey:
        name:
          - git
# install fails          - git-helper
          - sourcetree
          - gradle
          - maven
          - openjdk11
        state: present

    - name: "install basic tools packages"
      win_chocolatey:
        name:
          - 7zip
          - 7zip.install
          - curl
          - telnet
          - putty
          - microsoft-windows-terminal
          - winscp.install
          - gpg4win
          - keepass.install
          - keystore-explorer.portable
        state: present

    - name: "install multimedia packages"
      win_chocolatey:
        name:
          - gimp
          - paint.net
          - vlc
          - inkscape
          - plantuml
          - graphviz
          - adobereader
          - drawio
          - microsoft-teams
        state: present

    - name: "install web browsers"
      win_chocolatey:
        name:
          - firefox
          - googlechrome
        state: present

    - name: "install dev/test tool packages"
      win_chocolatey:
        name:
          - vmware-horizon-client
          - notepadplusplus.install
          - wireshark
          - telnet
          - docker-desktop
        state: present

    - name: "install IDE packages"
      win_chocolatey:
        name:
          - vscode
          - jetbrainstoolbox
          - intellijidea-ultimate
        state: present

# uninstall geht über absent muss aber teilweise zweimal gemacht werden z.b.
# 1) vlc 2) vlc.install obwohl nur eines installiert wurde
