---
- name: Setup of Dev environment for native windows client
  hosts: all  
  tasks:    
    - name: "Install chocolatey"
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
           - chocolatey-windowsupdate.extension
           - chocolatey-dotnetfx.extension
          state: present
    - name: install basic dev packages
      win_chocolatey:
        name: 
          - git
# install fails          - git-helper
          - sourcetree
          - gradle
          - maven
          - openjdk11
          - curl
        state: present

    - name: install multimedia packages
      win_chocolatey:
        name: 
          - gimp
          - vlc
          - inkscape
          - plantuml
          - graphviz
        state: present
          
    - name: install browsers
      win_chocolatey:
        name: 
          - firefox
          - googlechrome
        state: present

    - name: install dev/test tool packages
      win_chocolatey:
        name: 
          - vmware-horizon-client        
          - notepadplusplus.install
          - wireshark
          - telnet
          - putty
          - keystore-explorer.portable
        state: present

    - name: install IDE packages
      win_chocolatey:
        name: 
          - vscode
          - jetbrainstoolbox
          - intellijidea-ultimate
        state: reinstalled
        
    - name: Check to see if Docker is installed
      win_stat: path='C:\Program Files\Docker'
      register: docker_installed  
    - name: Check to see if Docker file is downloaded
      win_stat: 
        path: 'C:\temp\DockerDesktopInstaller.exe'
      register: docker_downloaded
    - name: Download Docker installer
      win_get_url:
        url: 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe'
        dest: 'c:\temp\DockerDesktopInstaller.exe'
      when: not docker_downloaded.stat.exists
      
    - name: Install Docker Desktop
      ansible.windows.win_shell: 'c:\temp\DockerDesktopInstaller.exe install --quiet'
      when: not docker_installed.stat.exists
        
        
# uninstall geht über absent muss aber teilweise zweimal gemacht werden z.b.
# 1) vlc 2) vlc.install obwohl nur eines installiert wurde
