---
- name: "install basic ubuntu components"
  hosts: all
  become: yes
  tasks:
    - name: "ensure basic ubuntu components is installed"
      apt:
        name:
          - openconnect
          - network-manager-openconnect
          - network-manager-openconnect-gnome
          - bash
          - curl
          - gpg
          - git
          - wget
          - openssh-client
          - openssl
          - ubuntu-desktop
          - expect
        state: present
        update_cache: yes

- name: "install ubuntu multimedia components"
  hosts: all
  become: yes
  tasks:
    - name: "ensure ubuntu multimedia components is installed"
      apt:
        name:
          - graphviz
          - gimp
          - inkscape
          - vlc
        state: present
        update_cache: yes

- name: "install ubuntu mozilla components"
  hosts: all
  become: yes
  tasks:
    - name: "ensure ubuntu communications components is installed"
      apt:
        name:
          - firefox
          - thunderbird
          - gajim
        state: present
        update_cache: yes


- name: "install ubuntu misc components"
  hosts: all
  become: yes
  tasks:
    - name: "ensure ubuntu misc components is installed"
      apt:
        name:
          - rdesktop
          - virtualbox
        state: present
        update_cache: yes

- name: "install java & dev components"
  hosts: all
  become: yes
  tasks:
    - name: "ensure java & dev components is installed"
      apt:
        name:
          - wireshark
          - tshark
          - maven
          - openjdk-11-jdk
          - plantuml
          - python2
          - python3
          - python3-pip
          - telnet
        state: present
        update_cache: yes

- name: "Install python packages"
  hosts: all
  tasks:
    - name: "install vpn-slice"
      pip:
        name:
          - https://github.com/dlenski/vpn-slice/archive/master.zip

- name: "Basic Java settings"
  hosts: all
  become: yes
  tasks:
    - name: "set JAVA_HOME"
      lineinfile:
        path: /etc/environment
        regexp: 'JAVA_HOME'
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/'

- name: "install non-native software components"
  hosts: all
  become: yes
  roles:
    - pixelart.chrome
    - ngetchell.vscode
    - geerlingguy.docker
    - alvistack.libreoffice
    - ngetchell.ms_teams
    - role: jetune.gradle
      vars:
        v_major: 5
        v_minor: 5.1
        is_default: true
    - role: gantsign.intellij
      vars:
        intellij_edition: ultimate

- name: "add keystore explorer"
  hosts: all
  become: yes
  tasks:
    - name: Install deb package
      apt:
        deb: https://github.com/kaikramer/keystore-explorer/releases/download/v5.4.4/kse_5.4.4_all.deb

- name: "install simple gematik vpn"
  hosts: all
  tasks:
    - name: "copy vpn script"
      ansible.builtin.copy:
        src: gematikvpn_simple
        dest: /usr/bin/gematikvpn_simple
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    
